### ISSUE TITLE
About the performanfe of td3bc on antmaze

### ISSUE THREAD

**Issue by sglucas** [fuyw/jrlzoo#10]
Hi

I try to run the code of td3bc on antmaze-medium-play-v0 and I find the performance (is 0) is lower than the results in iql paper (10.6). May I ask the experimental setting about that?

Thank you very much!

**Comment by fuyw** [comment]
I didn't tune the parameters for td3bc on antmaze-medium-play-v0. You can look for the original TD3BC paper, I remember the parameters are different for the antmaze task, which are described in the appendix.
